[versions]
kotlin = "2.3.0"
kotlinter = "5.3.0"
dokka = "2.1.0"
shadow = "9.3.0"
git-version = "4.2.0"
plugin-yml = "0.8.0"
minecraft-server = "4.0.1"
maven-publish = "0.35.0"
commandapi = "11.1.0"
paper = "1.20.4-R0.1-SNAPSHOT"
velocity = "3.4.0-SNAPSHOT"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
dokka-javadoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
git-version = { id = "com.palantir.git-version", version.ref = "git-version" }
plugin-yml-bukkit = { id = "de.eldoria.plugin-yml.bukkit", version.ref = "plugin-yml" }
minecraft-server = { id = "dev.s7a.gradle.minecraft.server", version.ref = "minecraft-server" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }

[libraries]
commandapi-bukkit-core = { group = "dev.jorel", name = "commandapi-bukkit-core", version.ref = "commandapi" }
commandapi-spigot-core = { group = "dev.jorel", name = "commandapi-spigot-core", version.ref = "commandapi" }
commandapi-paper-core = { group = "dev.jorel", name = "commandapi-paper-core", version.ref = "commandapi" }
commandapi-velocity-core = { group = "dev.jorel", name = "commandapi-velocity-core", version.ref = "commandapi" }
commandapi-paper-shade = { group = "dev.jorel", name = "commandapi-paper-shade", version.ref = "commandapi" }
commandapi-paper-kotlin = { group = "dev.jorel", name = "commandapi-kotlin-paper", version.ref = "commandapi" }
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
velocity-api = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
