[versions]
kotlin = "1.9.23"
kotlinter = "4.3.0"
dokka = "1.9.20"
shadow = "8.1.1"
git-version = "3.0.0"
plugin-yml = "0.6.0"
minecraft-server = "3.2.1"
commandapi = "11.1.0"
paper = "1.20.4-R0.1-SNAPSHOT"
velocity = "3.4.0-SNAPSHOT"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
git-version = { id = "com.palantir.git-version", version.ref = "git-version" }
plugin-yml-bukkit = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "plugin-yml" }
minecraft-server = { id = "dev.s7a.gradle.minecraft.server", version.ref = "minecraft-server" }

[libraries]
commandapi-bukkit-core = { group = "dev.jorel", name = "commandapi-bukkit-core", version.ref = "commandapi" }
commandapi-spigot-core = { group = "dev.jorel", name = "commandapi-spigot-core", version.ref = "commandapi" }
commandapi-paper-core = { group = "dev.jorel", name = "commandapi-paper-core", version.ref = "commandapi" }
commandapi-velocity-core = { group = "dev.jorel", name = "commandapi-velocity-core", version.ref = "commandapi" }
commandapi-spigot-shade = { group = "dev.jorel", name = "commandapi-spigot-shade", version.ref = "commandapi" }
commandapi-paper-kotlin = { group = "dev.jorel", name = "commandapi-kotlin-paper", version.ref = "commandapi" }
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
velocity-api = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
